---
abstract: 'Flash XMLSocket Server.'
author:
  - 'Takeshi Miki <miki@cpan.org>'
build_requires:
  FindBin::libs: 0
  IO::Socket: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Hoppy
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::Accessor::Fast: 0
  Class::Data::ConfigHash: 0
  Data::GUID: 0
  EV: 0
  Encode: 0
  Encode::Guess: 0
  Filter::Util::Call: 0
  JSON: 0
  POE: 0
  POE::Component::Server::TCP: 0
  POE::Filter::Line: 0
  POE::Sugar::Args: 0
  UNIVERSAL::require: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.01005
